name: Steam Metrics

on:
  schedule:
    - cron: "0 */6 * * *"
  workflow_dispatch:

permissions:
  contents: write

jobs:
  github-metrics:
    runs-on: ubuntu-latest
    steps:
      - name: Recently played games
        uses: lowlighter/metrics@latest
        with:
          filename: metrics.plugin.steam.svg
          token: ${{ secrets.GITHUB_TOKEN }}
          base: ""
          plugin_steam_token: ${{ secrets.STEAM_TOKEN }}
          plugin_steam: yes
          plugin_steam_user: "76561198188649533"
          plugin_steam_sections: recently-played
          plugin_steam_achievements_limit: 2

      - name: Profile and detailed game history
        uses: lowlighter/metrics@latest
        with:
          filename: metrics.plugin.steam.full.svg
          token: ${{ secrets.GITHUB_TOKEN }}
          base: ""
          plugin_steam_token: ${{ secrets.STEAM_TOKEN }}
          plugin_steam: yes
          plugin_steam_user: "76561198188649533"
          plugin_steam_sections: player, most-played, recently-played
          plugin_steam_games_limit: 1
          plugin_steam_recent_games_limit: 1
          plugin_steam_achievements_limit: 2
